#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinStore.Resource", IsApplication=true)]

namespace XamarinStore
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int add_to_basket_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int basket_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int enter = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int exit = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int product_detail_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int product_detail_out = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int ab_background = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ab_bottom_shadow_1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ab_bottom_shadow_2 = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int action_bar_title_color = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int btn_bg_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int btn_bg_shadow_color = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int main_background = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int xam_blue = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int xam_dark_blue = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int xam_gray = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int xam_green = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int xam_light_gray = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int xam_purple = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int btn_corner_radius = 2131230720;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_shirt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_bg_inactive = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_bg_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_bg_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int buttonimage = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cart = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int complete = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int configure = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int discrete_shadow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dummy_avatar = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int empty_basket = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int gallery_next = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int gallery_prev = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_basket = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_logo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int monkey = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int monoandroidsplash = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int processing = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ProductImage = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int purple_shirt = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int shirt_image = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int user_default_avatar = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int wrench = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0025
			public const int City = 2131361829;
			
			// aapt resource value: 0x7f0a0027
			public const int Country = 2131361831;
			
			// aapt resource value: 0x7f0a0020
			public const int FirstName = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int LastName = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int Phone = 2131361826;
			
			// aapt resource value: 0x7f0a0029
			public const int PlaceOrder = 2131361833;
			
			// aapt resource value: 0x7f0a0026
			public const int PostalCode = 2131361830;
			
			// aapt resource value: 0x7f0a0028
			public const int State = 2131361832;
			
			// aapt resource value: 0x7f0a0023
			public const int StreetAddress1 = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int StreetAddress2 = 2131361828;
			
			// aapt resource value: 0x7f0a000b
			public const int SwipeAfter = 2131361803;
			
			// aapt resource value: 0x7f0a0002
			public const int SwipeContainer = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int SwipeContent = 2131361795;
			
			// aapt resource value: 0x7f0a001c
			public const int addToBasket = 2131361820;
			
			// aapt resource value: 0x7f0a0010
			public const int bragButton = 2131361808;
			
			// aapt resource value: 0x7f0a000e
			public const int button1 = 2131361806;
			
			// aapt resource value: 0x7f0a002a
			public const int cart_menu_item = 2131361834;
			
			// aapt resource value: 0x7f0a0000
			public const int checkoutBtn = 2131361792;
			
			// aapt resource value: 0x7f0a0016
			public const int codeTextView = 2131361814;
			
			// aapt resource value: 0x7f0a0015
			public const int contentArea = 2131361813;
			
			// aapt resource value: 0x7f0a0018
			public const int descriptionLayout = 2131361816;
			
			// aapt resource value: 0x7f0a0011
			public const int email = 2131361809;
			
			// aapt resource value: 0x7f0a0014
			public const int error = 2131361812;
			
			// aapt resource value: 0x7f0a0017
			public const int explanationTextView = 2131361815;
			
			// aapt resource value: 0x7f0a001d
			public const int frameLayout1 = 2131361821;
			
			// aapt resource value: 0x7f0a0001
			public const int imageView1 = 2131361793;
			
			// aapt resource value: 0x7f0a000f
			public const int linearLayout1 = 2131361807;
			
			// aapt resource value: 0x7f0a0005
			public const int linearLayout2 = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int linearLayout3 = 2131361798;
			
			// aapt resource value: 0x7f0a0012
			public const int password = 2131361810;
			
			// aapt resource value: 0x7f0a000a
			public const int productColor = 2131361802;
			
			// aapt resource value: 0x7f0a0019
			public const int productDescription = 2131361817;
			
			// aapt resource value: 0x7f0a0004
			public const int productImage = 2131361796;
			
			// aapt resource value: 0x7f0a001e
			public const int productImageSpinner = 2131361822;
			
			// aapt resource value: 0x7f0a0008
			public const int productPrice = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int productSize = 2131361801;
			
			// aapt resource value: 0x7f0a0007
			public const int productTitle = 2131361799;
			
			// aapt resource value: 0x7f0a001f
			public const int scrollView1 = 2131361823;
			
			// aapt resource value: 0x7f0a0013
			public const int signInBtn = 2131361811;
			
			// aapt resource value: 0x7f0a001a
			public const int tableLayout1 = 2131361818;
			
			// aapt resource value: 0x7f0a000c
			public const int textView1 = 2131361804;
			
			// aapt resource value: 0x7f0a001b
			public const int textView4 = 2131361819;
			
			// aapt resource value: 0x7f0a000d
			public const int view1 = 2131361805;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Basket = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BasketItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BragScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PrefillXamarinAccountInstructions = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ProductDetail = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ProductListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ShippingDetails = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int XamarinListLayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int brag_on = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int brag_to_friends = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int XamActionBarStyle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int XamActionBarTheme = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int XamActionBarTitleStyle = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int XamButton = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int XamSubtitleText = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int XamTitleText = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
