#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MedConnect.Droid.Resource", IsApplication=true)]

namespace MedConnect.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_brightness = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_compose = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_download = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_expand = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_heart = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_library = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_menu = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_plus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_profle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_search = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_upload = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int logo2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int logo3 = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
